insert into lemondb.categories (text) values 
("Action/Adventure"),
("Action/Comedy"),
("Animation"),
("Anime"),
("Ballet"),
("Comedy"),
("Comedy/Drama"),
("Dance/Ballet"),
("Documentary"),
("Drama"),
("Drama/Silent"),
("Exercise"),
("Family"),
("Fantasy"),
("Foreign"),
("Games"),
("Horror"),
("Karaoke"),
("Late Night"),
("Music"),
("Musical"),
("Mystery/Suspense"),
("Opera"),
("Satire"),
("SciFi"),
("SciFI"),
("Silent"),
("Software"),
("Special Interest"),
("Sports"),
("Suspense/Thriller"),
("Thriller"),
("TV Classics"),
("VAR"),
("War"),
("Western");